# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Ricco
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John
  url:               https://twitter.com/riccoja
  email:             johnricco226@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
    About: '/about'
    Research and projects: '/projects'